KEY: "trackback_key"
visible: "1"

NAME: "1stlog"
VERSION: "Ver1.2.0.0"
RELEASE_TIME: "2008.04.20"
HOMEPAGE: "http://1stlog.1sters.com"

AUTHOR: "IceskYsl@1sters!"
AUTHOR_EMAIL: "iceskysl@gmail.com"
AUTHOR_BLOG: "http://iceskysl.1sters.com"
